### ISSUE TITLE
MessageFormat uses JSON for resource bundles, but ICU4J uses something else

### ISSUE THREAD

**Issue by alex-dow** [SlexAxton/messageformat.js#106]
ICU4J uses this: http://userguide.icu-project.org/locale/resources

MessageFormat appears to use JSON.

Is there any way to consolidate the two so I can share resources between client and server code?

**Comment by SlexAxton** [comment]
I think the best case scenario would be a converter from their resource format to json, but I don't think it'd be wise to force front-end folks to use that one-off format (that has a lot of C error handling stuff, etc) with messageformat.js.

It's actually a good candidate for a separate project icu-resouce-file-to-json

Unlike messageformat itself, there's actually a formal definition for the format: http://source.icu-project.org/repos/icu/icuhtml/trunk/design/bnf_rb.txt -- I'd imagine someone could run that through a parser generator and create a pretty quick little converter.

**Comment by alex-dow** [comment]
if one must: https://github.com/alex-dow/icu-converter

 ;)

How does MessageFormat handle a hierarchy of values? eg:

```javascript
{
    "menu": {
        "file": "File"
        "exit": "Exit"
    }
}
```
In the examples, there is some hierarchy by having files in separate folders it seems, but will it handle it in JSON as well?

**Comment by alex-dow** [comment]
also, I feel I should say a big thanks for this project. Not only is this project in my opinion the best approach for cross-browser, non-polyfill, highly efficient localization, but your pegjs file helped me immensely to understand PEG and pegjs.

**Comment by alex-dow** [comment]
ok, MessageFormat handles hierarchies just fine. A resource bundle that looks like:

```
en {
    menu {
        item { "string message" }
    }
}
```

will end up as mfunc().en.menu.item;

which I guess you already know but figured someone might also want to ask ;)

**Comment by alex-dow** [comment]
Alright, the converter is pretty much done to an acceptable level now. binary, imports, and aliases aren't supported, but everything else (including it's valuable flexible string syntax) is done and tested. I guess I'll close this as it's not an issue and instead just a soapbox for my ramblings.

Again, thank you for this project as it has helped me a great deal.

**Comment by SlexAxton** [comment]
The issue isn't closed til you PR our README with a link. :D

**Comment by alex-dow** [comment]
haha fair enough, I'll get around to that sometime this weekend I guess.

**Comment by alex-dow** [comment]
https://github.com/SlexAxton/messageformat.js/pull/123

Sorry this took er... months? It had just completely slipped my mind!

**Comment by SlexAxton** [comment]
Mine too!
