### ISSUE TITLE
Version on Github is 0.3.0, on npm still 0.2.2

### ISSUE THREAD

**Issue by gotofritz** [SlexAxton/messageformat.js#107]
Hi.

The version of messageformat on npm seems to be out of date - it's still 0.2.2
https://www.npmjs.com/package/messageformat

**Comment by SlexAxton** [comment]
We haven't officially release 0.3.0 since we haven't written docs for the changes. Hopefully soon, though!

**Comment by eemeli** [comment]
And in the meantime, you can install the latest via npm with:

```
npm install messageformat@prerelease
```

**Comment by gotofritz** [comment]
Thanks, that works

**Comment by puspa** [comment]
Is there any word on when 0.3.0 will be released?

We are having issues with v0.2.2 when using babel-loader with webpack.  The prerelease version works fine.

**Comment by eemeli** [comment]
@SlexAxton, should I take over the task of updating the docs? Not sure how soon I'll get to doing anything about them, but clearly as is we're not getting this forward.

**Comment by SlexAxton** [comment]
Sounds fine to me

**Comment by gregglind** [comment]
(I suspect this what is causing the issues with #125 as well!  Docs "sort of" work with the 0.3.0 release :)  )

**Comment by eemeli** [comment]
Closing this due to finally releasing [`0.3.0`](/SlexAxton/messageformat.js/releases/tag/v0.3.0).
