### ISSUE TITLE
Installing messageformat with npm from github is all over the shop

### ISSUE THREAD

**Issue by gotofritz** [SlexAxton/messageformat.js#108]
Hi

If I have this in my package.json

     "devDependencies": {
        "messageformat": "SlexAxton/messageformat.js#0.3.0-0"
     }

and do a `npm install` all seems good. But when I try to bundle messageformat with webpack I get all sort of errors which I don't get with the npm version

    WARNING in ./~/messageformat/~/make-plural/make-plural.js
    Critical dependencies:
    192:49-71 the request of a dependency is an expression
     @ ./~/messageformat/~/make-plural/make-plural.js 192:49-71

    WARNING in ./~/messageformat/~/make-plural/package.json
    Module parse failed: /PATH//node_modules/messageformat/node_modules/make-plural/package.json Line 2: Unexpected token :
    You may need an appropriate loader to handle this file type.
    | {
    |   "name": "make-plural",
    |   "version": "2.1.3",
    |   "description": "Translates Unicode CLDR pluralization rules to executable JavaScript",
     @ ./~/messageformat/~/make-plural ^\.\/.*$

    WARNING in ./~/messageformat/~/make-plural/LICENSE
    Module parse failed: /PATH//node_modules/messageformat/node_modules/make-plural/LICENSE Line 1: Unexpected number
    You may need an appropriate loader to handle this file type.
    | Copyright (c) 2014, Eemeli Aro <eemeli@gmail.com>
    | 
    | Permission to use, copy, modify, and/or distribute this software for any
     @ ./~/messageformat/~/make-plural ^\.\/.*$

    WARNING in ./~/messageformat/~/make-plural/bin/make-plural
    Module parse failed: /PATH//node_modules/messageformat/node_modules/make-plural/bin/make-plural Line 1: Unexpected token ILLEGAL
    You may need an appropriate loader to handle this file type.
    | #!/usr/bin/env node
    | 
    | /** A minimal/sample interface for make-plural.js
     @ ./~/messageformat/~/make-plural ^\.\/.*$

    WARNING in ./~/messageformat/~/make-plural/README.md
    Module parse failed: /PATH//node_modules/messageformat/node_modules/make-plural/README.md Line 2: Unexpected token ===
    You may need an appropriate loader to handle this file type.
    | make-plural
    | ===========
    | 
    | A JavaScript module that translates [Unicode CLDR](http://cldr.unicode.org/)
     @ ./~/messageformat/~/make-plural ^\.\/.*$

    WARNING in ./~/messageformat/~/make-plural/data/unicode-cldr-ordinal-rules.json
    Module parse failed: /PATH//node_modules/messageformat/node_modules/make-plural/data/unicode-cldr-ordinal-rules.json Line 2: Unexpected token :
    You may need an appropriate loader to handle this file type.
    | {
    |   "supplemental": {
    |     "version": {
    |       "_cldrVersion": "26",
     @ ./~/messageformat/~/make-plural ^\.\/.*$

    WARNING in ./~/messageformat/~/make-plural/data/unicode-cldr-plural-rules.json
    Module parse failed: /PATH//node_modules/messageformat/node_modules/make-plural/data/unicode-cldr-plural-rules.json Line 2: Unexpected token :
    You may need an appropriate loader to handle this file type.
    | {
    |   "supplemental": {
    |     "version": {
    |       "_cldrVersion": "26",
     @ ./~/messageformat/~/make-plural ^\.\/.*$

**Comment by SlexAxton** [comment]
All these failures are on non-javascript files. Unsure why it's changed between the two versions, but I assume there's something you can do in webpack to ignore non-js files.

**Comment by SlexAxton** [comment]
(The make-plural dependency is new as of 0.3.0)

**Comment by gotofritz** [comment]
Installing via npm with the @prerelease tag as suggested in issue 107 solves the problem - so it's either something to do with npm or with webpack. Thanks, closing issue.
