### ISSUE TITLE
Ship minified version

### ISSUE THREAD

**Issue by kdex** [SlexAxton/messageformat.js#110]
The `Angular` module `angular-translate-interpolation-messageformat` uses `messageformat.js` in order to support pluralization and other features.

As you might expect, this means that many browsers are in need of `messageformat.js`. At the moment, however, all that's shipped is an overly verbose (that is, unminified) version that is not suitable for the web at **47.7 KiB** (this is a *lot*).

Most package maintainers therefore minify their scripts for browsers so that users can use tools such as `wiredep` to automatically hook up all bower modules into their markup and tools such as `usemin` to bundle them into one big file. This has one big advantage: Users can have their dependencies minified in a file without having to minify even one line themselves. Build time will therefore dramatically decrease for everyone.

With a potential **21.8 KiB**, messageformat.js could highly benefit from shipping a minified version.

So, erm: Pretty please? :)

**Comment by SlexAxton** [comment]
Thank you for the thoughtful explanation.

I'm not 100% opposed to this, but if it's performance you're after, offering a minified version seems like it's promoting a bad practice.

If you want the best performance, you'll already need a process for bundling scripts and minifying them. I think offering a minified version has fallen out of favor because it implies that someone would include your script as a separate resource.

When the script isn't minified in dev mode, the errors are also easier to understand, and source maps can work nicely after your build process has run, even in production.

Is there a scenario, where providing minified version is going to promote the best practice, that I'm missing?

**Comment by SlexAxton** [comment]
(Also, during the build process, people should be precompiling their templates and then only including the vastly smaller messageformat.runtime.js - bundling that - and then minifying all of it.)

**Comment by kdex** [comment]
Well, alongside minified versions, most bower package maintainers (compare [bower-angular](https://github.com/angular/bower-angular), [jQuery](https://github.com/components/jquery), [underscore](https://github.com/jashkenas/underscore) and others) do also ship source maps themselves.

Although I can follow that shipping minified versions doesn't seem like "good practice" at first (since it feels equally bad as committing binary formats to a repository), there are scenarios where this is beneficial:

Consider the use of `messageformat.js` from a `bower` point of view. Bower specifies a `main` property in `bower.json`. `main` takes an array of strings representing relative paths to certain files in your bower package.

A common workflow for web developers is to specify a task in their build files that bundles all the scripts that the bower dependencies have in their `main` property. This blends in perfectly for `dev` versions, but it doesn't really scale well if you have a lot of dependencies, since you now need to minify every single dependency yourself (which can be a matter of minutes on a fast machine, even).

This is why bundlers such as `wiredep` allow you to override the `main` property with a custom value, directing `wiredep` to a pre-compiled version of the same script (that is usually shipped along with the script). This means that you can have your minified `lib.js` (or whatever) by just **concatenating shipped minifications** instead of **minifying shipped sources**.

If you volunteer to ship the source maps as well, people can use them as input for their concatenations, so there's no real advantage in making source maps yourself for every project; it just takes longer. Even in "dev mode", you don't want to wait that long. :) There's already projects that can [handle this](https://github.com/mikach/gulp-concat-sourcemap).

So, maybe it would feel "cleaner" if you shipped a minified version to `bower` only?
Oh and, could you elaborate on the point that shipping minified versions might promote a bad practice?

**Comment by kdex** [comment]
Also, beware that some errors can also happen in the process of minification itself, so it can be crucial to test the script both ways: Minified and unminified (as an example, see `Angular`'s *Dependency Injection* model that depends on actual variable names, at least for the current stable written for EcmaScript 5).

**Comment by eemeli** [comment]
Closing, as this got implemented in #137.
