### ISSUE TITLE
Add semicolons at the end of locale files

### ISSUE THREAD

**Issue by szimek** [SlexAxton/messageformat.js#111]
I have no idea where files with pluralization rules in `locale` folder come from, but they don't have semicolons at the end and this may cause some really strange and hard to find bugs when these files are concatenated with other third-party library files. Here's an example from our app: http://jsfiddle.net/szimek/1xrzqgmm/3

**Comment by SlexAxton** [comment]
In current master, and future releases all plural files are generated with `make-plural` which sources directly from CLDR. So I think this has more or less already been fixed.

(I would suggest smarter build tools than just "concat blindly" though.)

**Comment by SlexAxton** [comment]
Thanks for the report!

**Comment by szimek** [comment]
For those who by any chance have the same issue and use `gulp-concat` - turns out it has `newLine` option, so calling it like `concat("output.js", {newLine: "\n;"})` fixes this problem.
