### ISSUE TITLE
Content Security Policies clash with `new Function`

### ISSUE THREAD

**Issue by unindented** [SlexAxton/messageformat.js#112]
Places like the Chrome Store have a pretty strict `Content Security Policies` setting, that throw an `unsafe-eval` error when encountering things like `eval` and `new Function`.

@SlexAxton How hard would it be to replace these `new Function` calls with alternatives?

**Comment by rxaviers** [comment]
@SlexAxton may give you a proper response... But, a suggestion is to precompile your formatters during build time and to deploy only these runtime functions.

**Comment by SlexAxton** [comment]
Yea, I believe all `new Function` and `eval` work is done in development mode. The precompilation step will remove the entire compiler from your runtime, as well as remove any need for `eval` or `new Function`

**Comment by SlexAxton** [comment]
(I use messageformat.js in a very locked down CSP environment, currently)

**Comment by unindented** [comment]
Aah right right. I'll close this.

I came across this problem while using `globalize`, so @rxaviers could you give me some hints on how to precompile my translations? `Globalize.messageFormatter` seems to compile at runtime: https://github.com/jquery/globalize/blob/fe14f5b1ccd14ee9af9bf0eb903d758f3d54973f/src/message.js#L93

**Comment by rxaviers** [comment]
@unindented, absolutely. Globalize automates that for you (as soon as #398 lands :smile: - probably this week). I will post two examples there, one using webpack and another one using AMD+r.js.

**Comment by unindented** [comment]
That's great news. Thank you so much @rxaviers!
