### ISSUE TITLE
Default value for variable substitution

### ISSUE THREAD

**Issue by tuhoojabotti** [SlexAxton/messageformat.js#113]
Let's say I have a message `"{name} works for company..."` on a user creation form. When the user hasn't entered any name yet, the result will be `"undefined works for company"`. Now I could give the default value myself, but the information should be in the translation, not in the application logic.

For example `"{name, default, {User}} works for company..."`,
or just `"{name | User} works for company..."`

Maybe I'm missing something?

**Comment by SlexAxton** [comment]
I have just implemented the ICU MessageFormat spec in JS, so I'm not really in charge of adding new features.

There's no shorthand for what you want, but you probably either want separate messages and a smarter template:

```handlebars
{{#if userHasFilledOutField}}
  <span>{{mf key="message.worksfor"}}</span>
{{else}}
  <span>{{mf key="message.worksforteaser"}}</span>
{{/if}}
```

or to use SelectFormat if for some reason you think the branching would be locale dependent (requires you to send extra state data into the message):

```messageformat
{formIsFilled, select,
  true {{name} works for company}
  other {They work for company}
}
```

Hope that helps!

**Comment by tuhoojabotti** [comment]
Thanks for the tips! I understand not wanting to add features that aren't part of the spec.

Making the template smarter is a bit tricky, because I want to use it in a placeholder attribute and it would make the template quite messy.

I was also thinking about using the select feature just before you replied, I might give it a shot. But if it seems hard I'll just drop it for a static string.

**Comment by eemeli** [comment]
Because the key values are cast to strings by JavaScript during the lookup, a value that is left undefined in the input data matches the string `'undefined'`. This "feature" means that the following form is probably what you're looking for:
```
{name, select, undefined{They work} other{{name} works}} for company
```

**Comment by tuhoojabotti** [comment]
Unfortunately the security strategy of angular-translate sanitizes undefined values to empty strings, but using `name || 'undefined'` as the value works nicely. Kiitos!

I guess it's a feature that `other{{name}}` doesn't work as a case alone and I have duplicate "works".
