### ISSUE TITLE
Help in using

### ISSUE THREAD

**Issue by robhicks** [SlexAxton/messageformat.js#114]
I'm trying to use messageformat and having problems getting what seems to be a simple pluralization working. 
Please see this [plunker](http://plnkr.co/edit/n72unBcUL7XZ2lt7a223?p=preview).
Thanks!

**Comment by SlexAxton** [comment]
Looks like an extra comma between the options that isn't in the syntax, as well as your script trying to run before the template element existed.

Here's a working version: http://plnkr.co/edit/q2OjB4c4LXMM9xmaplDr?p=preview

Thanks for asking!

**Comment by robhicks** [comment]
@SlexAxton Thanks!
