### ISSUE TITLE
Incorrect regex in v0.2.2

### ISSUE THREAD

**Issue by theking-laptop** [SlexAxton/messageformat.js#115]
@SlexAxton You might use incorrect regex and it fails in IE8:
https://github.com/SlexAxton/messageformat.js/blob/0.2.2/messageformat.js#L49

Should it be `.match(/{[\^]*}/)` or `.match(/{.*}/)` or `.match(/{.+}/)` ? Please fix this bug as soon as possible, thanks!

**Comment by eemeli** [comment]
Closing this due to finally releasing [`0.3.0`](/SlexAxton/messageformat.js/releases/tag/v0.3.0), which loads locales differently. Also, we have a new website at [messageformat.github.io](https://messageformat.github.io/).

**Comment by JimmyBoh** [comment]
@theking-laptop @eemeli  For those of us who are locked in to `v0.2.2` what is the correct regex?

**Comment by JimmyBoh** [comment]
[I think this should work](https://regex101.com/r/aO7qZ6/1)... Any thoughts?

**Comment by eemeli** [comment]
That won't match newlines. The original expression `/{[^]*}/` tries to match all characters within braces, which `.*` actually doesn't do. Try `/{[\s\S]*}/` instead.

**Comment by JimmyBoh** [comment]
Looks good, thanks!
