### ISSUE TITLE
Add language PT-BR

### ISSUE THREAD

**Issue by phouverneyuff** [SlexAxton/messageformat.js#116]
Please duplicate locale pt with name pt-br

pt - Portugal
pt-br - Brazil

Both speak Portuguese, but we have a specific locale.

**Comment by rxaviers** [comment]
According to CLDR, `pt` defines Portuguese as spoken in Brazil (note pt-BR is the default content locale for pt); `pt-PT` defines Portuguese as spoken in Portugal.

http://cldr.unicode.org/translation/default-content

**Comment by SlexAxton** [comment]
Can you confirm that this is an issue in master with make-plural?

**Comment by SlexAxton** [comment]
Ah. Just saw Rafael's answer. Sounds right to me!

**Comment by eemeli** [comment]
The locale lookup in messageformat.js should also correctly find the `pt` rules for `pt-BR` ([0.2.2](/SlexAxton/messageformat.js/blob/0.2.2/lib/messageformat.dev.js#L36), [0.3.0-1](/SlexAxton/messageformat.js/blob/v0.3.0-1/lib/messageformat.js#L32)).

**Comment by eemeli** [comment]
Closing this due to finally releasing [`0.3.0`](/SlexAxton/messageformat.js/releases/tag/v0.3.0). Also, we have a new website at [messageformat.github.io](https://messageformat.github.io/).
