### ISSUE TITLE
Can't use \u005C

### ISSUE THREAD

**Issue by robertbastian** [SlexAxton/messageformat.js#118]
I'm trying to make MessageFormat work nicely with Markdown. I'm sending text through a Markdown parser first, and then through messageformat.js. Now, to preserve `\\` during Markdown compilation, I replaced them by `\\u005C`, so that after the Markdown parser is done, I'll have `\u005C` which messageformat.js should translate into a single backslash `\`. 

However, the backslash doesn't appear in the output. Following up, I came across this error:

```
(new MessageFormat('en')).compile('This is a backslash: \\u005C')
SyntaxError: Unexpected EOF
```

**Comment by eemeli** [comment]
This appears to be fixed in the just-released [`0.3.0`](/SlexAxton/messageformat.js/releases/tag/v0.3.0), so I'm closing this:

```js
> (new MessageFormat('en')).compile('This is a backslash: \\u005C')
[Function]
> (new MessageFormat('en')).compile('This is a backslash: \\u005C')()
'This is a backslash: \\'
```
