### ISSUE TITLE
Feature request: in precompiled functions, support anonymous arguments instead of an object

### ISSUE THREAD

**Issue by deltaidea** [SlexAxton/messageformat.js#121]
It would be sweet to be able to write this:

```JavaScript
var welcome = mf.compile("Welcome back, {$1}! It's {$2}.")
welcome("John", "Monday") // Welcome back, John! It's Monday.
```

This `sprintf`-like notation is shorter and easier to use, since naming stuff is [one of the hardest things in programming](https://twitter.com/codinghorror/status/506010907021828096).

Compiled function can look like this:

```JavaScript
function (a1, a2) { return "Welcome back, " + a1 + "! It's " + a2 + "."; }
```

.. or like this:

```JavaScript
function () { return "Welcome back, " + arguments[0] + "! It's " + arguments[1] + "."; }
```

Though the first option looks nicer.

It should be compatible with the current object-style notation:

```JavaScript
var welcome = mf.compile("Welcome back, {name}! It's {$2}.")
welcome({name: "John"}, "Monday") // Welcome back, John! It's Monday.
```

I'd consider that an anti-pattern, but the point is - you can use different styles for different messages, so old code won't break.

**Comment by deltaidea** [comment]
As a workaround, it's currently possible to use an array instead of an object, and then use indexes as keys:

```JavaScript
var welcome = mf.compile("Welcome back, {0}! It's {1}.")
welcome(["John", "Monday"]) // Welcome back, John! It's Monday.
```

But it's confusing to read, especially if there's only one argument.

**Comment by eemeli** [comment]
I'm not convinced that this would be a pattern that would prove "easier to use". Especially as we're talking about replacing words, it's hard to think of an actual example where an appropriate name could not be found for the variable in question. Your example, for instance, could work well as:
```js
var welcome = mf.compile("Welcome back, {name}! It's {day}.")
welcome({ name:"John", day:"Monday" }) // Welcome back, John! It's Monday.
```
... which has the added benefit of making it clear what the replacements are for. If using numerical indices only, `"Welcome back, {$1}! It's {$2}."` could just as easily turn into `"Welcome back, visitor! It's four o'clock."`

Also, given that the generated function requires some `{object}` or `[array]` notation for its input parameter, and that numerical indices already work with the latter, this seems like syntactic sugar that just adds complexity.

**Comment by deltaidea** [comment]
True. Now that I've found that arrays work as well, this feature is practically already implemented.
Thanks for your response. :)
