### ISSUE TITLE
Access object properties within message?

### ISSUE THREAD

**Issue by krues8dr** [SlexAxton/messageformat.js#127]
I looked through the documentation but couldn't find an easy answer - is there a way to refer to the properties of an object that's been passed to messageformat?  I'm using `angular-translate-interpolation-messageformat` with `angular-translate`, and want to be able to pass an object in to get properties out of it.  E.g., given a `doc` object that has a `title` property:

```
<span translate="objectTest"
  translate-values="{doc: doc}"
  translate-interpolation="messageformat"></span>
```

With the following translation:

```
  "objectTest": "{doc.title}"
```

But that throws an error.  I've also tried `doc[title]` and `doc['title']` but they both return undefined.  Any other way to do this that I'm missing?  It works fine without messageformat interpolation.

**Comment by SlexAxton** [comment]
Since messageformat is a standard that exists outside of JavaScript, we've implemented it in a way that makes it the most interoperable with other runtimes. Because the messageformat standard doesn't have any object property notation, we did not add it to messageformat.js

I actually kind of find it nice to flatten objects beforehand, though. It's a more explicit declaration of the values you might use in the message.

```html
<span translate="objectTest"
  translate-values="{title: doc.title}"
  translate-interpolation="messageformat"></span>
```

```json
{
  "objectTest": "{doc.title}"
}
```

**Comment by krues8dr** [comment]
Great, thanks.

**Comment by eemeli** [comment]
Actually, getting this to work in MessageFormat is pretty simple. I'm not sure though how to do this within the Angular module, but here's something that works in JS, using MessageFormat 0.3 (still in pre-release):
```js
var fmt = { prop: function(v, lc, p) { return v[p] } },
    mf = new MessageFormat('en', null, fmt),
    fn = mf.compile('Age: {o, prop, age}');
fn({o: {x: 3, age: 42}})
> 'Age: 42'
```

So what's happening there is that we're using the third parameter of the MessageFormat constructor to pass in a custom formatting function `prop` that looks up the defined field from the input object.

A bit more information about these formatting functions, including the default ones, is available in the [API documentation](https://rawgit.com/SlexAxton/messageformat.js/v0.3.0-1/doc/MessageFormat.formatters.html).

@SlexAxton, this was discussed and implemented in PR #68.

**Comment by krues8dr** [comment]
Thanks @eemeli that's great!  I'll have to dig around a bit to see how I can implement this, since I've got a few layers of wrapper to negotiate here.

**Comment by eemeli** [comment]
I'm closing this, as 0.3 has already been out for a while, and remaining issues are probably more appropriate to address directly to the angular wrapper.

**Comment by kavi87** [comment]
I think this is an annoying limitation to be compliant with a spec that is itself not very good.

 For instance if you want to write messages with multiple context `Hello { SUBJECT.firstName }, you are consulting { OBJECT.reference } ...`. It is also not possible to use a custom formatter to use the result of evaluation as the variable, for instance `{ obj, prop, age}, select, 10{ Your are 10 } ... }`.  

I understand you want to stay compliant but after all, being compliant with the spec is the responsablity of the one who writes the message, nothing should prevent you from making the templating more powerful without custom code.
