### ISSUE TITLE
Boolean strings

### ISSUE THREAD

**Issue by mkoczorowski** [SlexAxton/messageformat.js#131]
Hi,
Does anyone know is it possible to do select based on some bool value like so :+1: 

{ {trueOrFalse}, select, true{yes} other{no} }

I would appreciate any help in this matter.

**Comment by xavhan** [comment]
Got the same problem, my workaround is to do as follow

in my view 
```html
<div>
  {{ ::"CONDITIONAL_TEXT_KEY" | translate : {
    trueOrFalse: myConditionWichReturnABoolean.toString()
  } : 'messageformat' }}
</div>
```
and in my json translation object : 
```json
{
  "CONDITIONAL_TEXT_KEY": "this is {trueOrFalse, select, true{my text when true} other{my text when false} }"
}
```

If someone has a cleaner solution I am all ears.

**Comment by mkoczorowski** [comment]
thats a very good idea! Thanks @xavhan

**Comment by eemeli** [comment]
As @xavhan noted, the variable values get cast to strings, so booleans work with `true` and `false` keys:
```js
var mf = new MessageFormat('en');
var fn = mf.compile('{ B, select, true{yes} false{no} undefined{maybe} other{B} }');
fn({ B: true });    // 'yes'
fn({ B: false });   // 'no'
fn({});             // 'maybe'
fn({ B: 'beep' });  // 'beep'
```
