### ISSUE TITLE
Error when using with at least 2 languages

### ISSUE THREAD

**Issue by PaulAnnekov** [SlexAxton/messageformat.js#134]
Each new `MessageFormat` instance creation totally removes (see it [here](https://github.com/SlexAxton/messageformat.js/blob/master/lib/messageformat.js#L66)) all plural functions from `MessageFormat.prototype.runtime.pluralFuncs` object that is shared accross all MessageFormat instances. Why do you do this?

You should remove this line or make `runtime`/`runtime.pluralFuncs` per-instance, not global.

This bug in Plunker:

1. Go to http://plnkr.co/edit/TZQ1VR2C0JNR1vaJNT4T?p=preview
2. Open console and see `Uncaught TypeError: lcfunc is not a function`

**Comment by eemeli** [comment]
Agreed, `runtime` should be per-instance. I'll take a look at it when I have time, hopefully within the next week or so. In the meantime, you can get multi-language instances to work [like this](http://plnkr.co/edit/AsS2t6HX8GbVsPEkLULL?p=preview).

**Comment by PaulAnnekov** [comment]
@eemeli 10x, but I use angular-translate with it's own wrapper, that I can't modify :). I will fork your repo and fix issue there in a fastest way.

**Comment by eemeli** [comment]
I fixed this by making `MessageFormat#runtime` a proper class of its own, so it's private to each instance. Also improved the documentation code examples a bit.

**Comment by PaulAnnekov** [comment]
@eemeli good, 10x :)
