### ISSUE TITLE
does messageformat-parser.js be need to be hosted on CDN?

### ISSUE THREAD

**Issue by maruilian11** [SlexAxton/messageformat.js#136]
hi, recently we want to add your lib on https://cdnjs.com, we prefer to use npm auto-update to add lib file and later version. i saw messageformat-parser.js put in lib folder in npm package, just want to confirm if `messageformat-parser.js` also need to be hosted in cdnjs?
thank you very much!

https://github.com/cdnjs/cdnjs/pull/6855

**Comment by SlexAxton** [comment]
It does not need to be on the cdn. Thanks!

**Comment by maruilian11** [comment]
thank you!
