### ISSUE TITLE
number format for numbers in e.g. plural formats

### ISSUE THREAD

**Issue by agibson-vrnt** [SlexAxton/messageformat.js#140]
Given a message format of

    Usted {numPhotos, plural, =0 {no tiene fotos.}
                              =1 {tiene una foto.}
                              other {tiene # fotos.}}
    

When I execute:

`new MessageFormat( "es-MX" ).compile( messageFormat )( { numPhotos: 1000 } )`

I would like to get the output:

` Usted tiene 1,000 fotos.`

However, instead I am receiving:

` Usted tiene 1000 fotos.`

Note the missing separator comma in the actual output. Is this possible with your library?

**Comment by eemeli** [comment]
Yes, it's possible, using the `number` [formatter function](https://messageformat.github.io/messageformat.js/doc/MessageFormat.formatters.html). Along with other updates, these are getting better documented in #138.

The formatters make use of the [`Intl`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) global object, which isn't yet available in all browsers, so you'd likely need to use a [polyfill](https://github.com/andyearnshaw/Intl.js/). You'll need to specifically enable that with `setIntlSupport`:

```js
var mf = new MessageFormat('es-MX').setIntlSupport();
var src = 'Usted {numPhotos, plural, =0 {no tiene fotos.} ' +
          '=1 {tiene una foto.} ' +
          'other {tiene {numPhotos, number} fotos.}}';
mf.compile(src)({ numPhotos: 1000 });
// 'Usted tiene 1,000 fotos.'
```

**Comment by eemeli** [comment]
Closing as answered.
