### ISSUE TITLE
An option to disable strict 'other' branch in plural and select

### ISSUE THREAD

**Issue by Strate** [SlexAxton/messageformat.js#141]
Hi!
I have a lot of messages, written without `other` branch for `plural` and `select` rules. can you provide an option to disable that check?

**Comment by eemeli** [comment]
Given that `other` is a pretty clear requirement of the ICU MessageFormat [plural](http://icu-project.org/apiref/icu4j/com/ibm/icu/text/PluralFormat.html) and [select](http://icu-project.org/apiref/icu4j/com/ibm/icu/text/SelectFormat.html) spec, the more appropriate fix here would be for you to add empty `other{}` cases to your messages -- I don't really see the benefit for us to break compatibility in this way.

If you'd like to customise your own implementation of messageformat.js, you're welcome to do so of course. The places to patch are on lines [259](/SlexAxton/messageformat.js/blob/master/lib/messageformat.js#L259), [269](/SlexAxton/messageformat.js/blob/master/lib/messageformat.js#L269), and [389](/SlexAxton/messageformat.js/blob/master/lib/messageformat.js#L389).

**Comment by Strate** [comment]
@eemeli I have a extra option `useDefaultOther` in my fork of this library. What could you say about this?

**Comment by eemeli** [comment]
I'm still not seeing the value of adding this to the API. Essentially, you're asking us to break compatibility with the spec by enabling more lax processing. What would be the benefit of doing that?

**Comment by Strate** [comment]
O would not name this "break compatibility". it is still compatible, but covers more variants.
As for me, it would be useful while migrating from https://github.com/yahoo/intl-messageformat library.

**Comment by eemeli** [comment]
Ah, ok. I was not aware that `intl-messageformat` had not implemented this requirement, so we're already in a situation where the implementations have diverged. I'll open an issue about this there, and hopefully we can get the two implementations unified.

**Comment by Strate** [comment]
As for me, this is not an issue anymore: I've upgraded all my messages by adding `default` rule. Close it if you want.

**Comment by eemeli** [comment]
Thanks for the update @Strate; I'll close this as it's really more of an issue with intl-messageformat.
