### ISSUE TITLE
Migrating FE project from bower to npm. No client file in npm package?

### ISSUE THREAD

**Issue by stnor** [SlexAxton/messageformat.js#142]
Hi.
I am in the process of migrating my front-end project from bower to npm.
I'm unable to find the client IFFE messageformat.js in the npm package?
It may be that I just need a good night sleep :)

Thanks!

**Comment by eemeli** [comment]
You're right; the release on npm does not (at least currently) include the compiled/IIFE version that's included in the bower and our GitHub releases. My gut feeling is that your case (using npm, but not e.g. Browserify or WebPack) is relatively rare; hence this decision.

There may, however, be some efficiencies to be made by publishing the compiled version on npm as well. Thoughts, @SlexAxton?

**Comment by SlexAxton** [comment]
I'm cool with that. We can make it a post-install build if we want, but
also fine with just checking it in to tags or whatever.

**Comment by stnor** [comment]
Thanks guys. Yeah still using requirejs here on a fairly large project. Eventually going webpack, bit not any time soon, so appreciated.

**Comment by arty-name** [comment]
I second that. I would really enjoy having in npm the same `messageformat.js` as in bower.

**Comment by eemeli** [comment]
Release [`v1.0.0-rc.2`](/SlexAxton/messageformat.js/releases/tag/v1.0.0-rc.2) now includes the compiled files. See [here](/SlexAxton/messageformat.js/pull/138#issuecomment-211124632) for installation instructions, if you're interested.

**Comment by stnor** [comment]
Thanks!
