### ISSUE TITLE
How to spell out numbers to words as a keyword/rule

### ISSUE THREAD

**Issue by stnor** [SlexAxton/messageformat.js#143]
Hi,
Is it possible to have a keyword/rule so that one can convert numbers to words eg 7 => 'seven' and reuse that rule in translation strings?

I would like to write out words for the numbers 1-10 in many translation strings.

I found this:
http://userguide.icu-project.org/formatparse/numbers
http://icu-project.org/apiref/icu4c/classRuleBasedNumberFormat.html

But I do not understand how to make this work in practice in my translation files / javascript.

Thanks.

/Stefan

**Comment by eemeli** [comment]
The rule-based number formatter is unfortunately not included in messageformat.js. However, we do have support for custom formatters, so if you are able to get a JavaScript function together that e.g. turns `17` into `"seventeen"`, I could help you in turning that into something like an extension of messageformat.js?

**Comment by stnor** [comment]
Ok cool, so here's a plunker: https://plnkr.co/edit/C7zUrAUsgmLrNlid2Dtl

**Comment by eemeli** [comment]
Here's a fork of your plunker that implements `spellOutNumber` as a custom formatting function: https://plnkr.co/edit/69F5lDzC0xEnP0LgDIdR

Your usage of '#' won't actually work as such, and it's pointing at a possible bug in the spec or implementation -- I'll post an issue about this, for consideration.

Regarding en/ett, are you sure that's an issue for you? Even in your example, you need a separate case for handling the singular. If it is an issue, the formatting functions can include additional parameters like `{numberOfTargets, spell, utrum}` which are passed to the function as an additional parameter.

**Comment by stnor** [comment]
Ok, great. That's awesome. Thanks a lot! Really appreciated!
Regarding the en/ett, I agree.
