### ISSUE TITLE
Preserve leading whitespace

### ISSUE THREAD

**Issue by alunny** [SlexAxton/messageformat.js#144]
Is there any way to preserve leading whitespace for a sub-message? Here is a concrete example:

```js
var MessageFormat = require('messageformat');
var msg = "Hello{COUNT, plural, =0{darkness} other{ world}}";

var mfunc = new MessageFormat('en').compile(msg);

console.log(mfunc({ COUNT: 0 }));
console.log(mfunc({ COUNT: 2 }));
```

I would like this to print:

```
Hellodarkness
Hello world
```

Instead it prints:

```
Hellodarkness
Helloworld
```

We just have a problem with one phrase in our app, so we'd prefer to fix this by changing the phrase, if possible, rather than changing any config options for the whole app. Also, we're using messageformat via Globalize, if that helps :shrug:

**Comment by SlexAxton** [comment]
That's definitely a bug. Will look into it.

**Comment by eemeli** [comment]
At the moment, whitespace just inside the `{}` separators is trimmed out, and there's even a [testcase](/SlexAxton/messageformat.js/blob/master/test/tests.js#L75) to make sure that happens.

For a quick fix, whitespace outside the `{}` is left intact, so you could use the following:
```js
var msg = "Hello {COUNT, plural, =0{darkness} other{world}}";
```

**Comment by SlexAxton** [comment]
Yea, I think the issue is that the space changes based on the case. @eemeli - do you think I was just being weird in the tests? Or is that a behavior that I'm forgetting should exist?

**Comment by alunny** [comment]
Yeah the spacing changes based on the case. I couldn't think of a legit example in English.

Here's the actual phrase that's causing us issues:

```
[userLink]{fullName}[/userLink] 님{otherUsersCount, plural, =0 {이 나를 팔로우합니다.} other { 외 #명이 나를 팔로우합니다.}}
```

**Comment by eemeli** [comment]
@SlexAxton: it's behaviour we've had since practically forever, so if we're going to change it, it'd be good to make it optional so we don't break any existing cases. I have no strong feelings about it. Maybe something like `MessageFormat.prototype.preserveWhitespace()`?

@alunny, in your example, you could bring in the `님` to the start of both of the `plural` cases; then the whitespace would be internal to the string, and left intact.

**Comment by alunny** [comment]
@eemeli that works for us. Thanks for the quick response!

**Comment by SlexAxton** [comment]
It feels like a bug, so I'd almost prefer to fix it and make an option to go back to the old functionality, and then put it out with a major release bump. We likely have your bug rewrite incoming, so it could pair well with that.

**Comment by SlexAxton** [comment]
*big rewrite (what a sad typo)

**Comment by eemeli** [comment]
Release [`v1.0.0-rc.2`](/SlexAxton/messageformat.js/releases/tag/v1.0.0-rc.2) no longer munges whitespace where it shouldn't. See [here](/SlexAxton/messageformat.js/pull/138#issuecomment-211124632) for installation instructions, if you're interested.
