### ISSUE TITLE
custom formatters don't work with 1.0.0-rc2

### ISSUE THREAD

**Issue by nkovacs** [SlexAxton/messageformat.js#147]
The `fmt` argument here: https://github.com/SlexAxton/messageformat.js/blob/v1.0.0-rc.2/lib/index.js#L253
is shadowed by the fmt variable here: https://github.com/SlexAxton/messageformat.js/blob/v1.0.0-rc.2/lib/index.js#L274
but the reduce callback wants to use the first one: https://github.com/SlexAxton/messageformat.js/blob/v1.0.0-rc.2/lib/index.js#L275

This fixes it:

```js
var fmtKey = Object.keys(compiler.formatters);
if (fmtKey.length) obj.fmt = fmtKey.reduce(function(o, key) { o[key] = fmt[key]; return o; }, {});
```

There's no branch for this tag, so I can't send in a pull request.

**Comment by eemeli** [comment]
Thank you for spotting this! The branch for this ended up [here](/eemeli/messageformat.js/tree/simpler-output) due to its origin as #138. Would you be ok submitting a PR against that branch, or would you prefer I add a commit to that effect myself?

**Comment by nkovacs** [comment]
I think it'd be quicker if you commited it.

**Comment by eemeli** [comment]
Fixed in [RC3](/SlexAxton/messageformat.js/releases/tag/v1.0.0-rc.3).
