### ISSUE TITLE
Browser formatted module in npm

### ISSUE THREAD

**Issue by RomainLK** [SlexAxton/messageformat.js#148]
npm is increasingly replacing bower as the package manager for front end dependency. While node is mainly using CommonJS format, I ( sadly ) have to use AMD on the front end. Would it be possible to bundle the `messageformat.js` from the bower package in the npm package?

edit: just saw that there is a RC. If it's enough I will close the issue.

**Comment by eemeli** [comment]
Yeah, this is included in the 1.0 RCs. If you need it before we're ready to publish a final version, you can use `npm install messageformat@prerelease`.
