### ISSUE TITLE
Can't find variable: module after updating

### ISSUE THREAD

**Issue by rgeraads** [SlexAxton/messageformat.js#149]
I'm trying to update messageformat.js from v0.1.8 to v0.3.1, but when trying run the app using Grunt, I get the following error:

`PhantomJS 1.9.8 (Linux 0.0.0) ERROR`
 `ReferenceError: Can't find variable: module
  at node_modules/messageformat/lib/messageformat.js:71
`

When loading the app via the browser the following errors pop up:
`messageformat.js:71 Uncaught ReferenceError: module is not defined`
`angular.js:4616 Uncaught TypeError: Cannot read property 'en' of undefined`

**Comment by eemeli** [comment]
In 0.3.1, `./lib/messageformat.js` expects to be run in an environment that supports CommonJS, such as node; hence the expectation to have `module` available. The compiled-for-browser version `./messageformat.js` isn't included in the npm release of that build, but it is in its bower release.

We've re-added the compiled version in the 1.0 npm builds, so I recommend you either switch to that, or use bower for including messageformat.js: `npm install messageformat@prerelease` or `bower install messageformat`.
