### ISSUE TITLE
Wrong plural rule detection for negative numbers

### ISSUE THREAD

**Issue by lukejagodzinski** [SlexAxton/messageformat.js#30]
I've found an error when trying to use negative numbers. Let' take an example.

"The temperature is -2 degrees."

For language like Polish it should get "few" rule but it gets "other" rule. In polish it behaves the same for positive and negative numbers. I don't know how the case looks in other languages.

The possible solution could be just taking absolute value of the number before detecting plural rule if the same situation takes place in other languages.

**Comment by vizo** [comment]
@jagi in ICU format it can be implemented like this:
```
> var msg =
              'NUM_PHOTOS': 'You have {numPhotos, plural, ' +
              '=-1 {# photo.}' +
              '=0 {no photos.}' +
              '=1 {# photo.}' +
              'other {# photos.}}',
```
I am from Slovenia so i had the same problem. :)

**Comment by jagi** [comment]
@vizo yes I know about that but that way you would have to write rules for all possible negative numbers :). So it's much better to just use absolute value for the number in Polish and Slovenian languages :). But it's very old problem for me, so I don't bother anymore, at least for now :) - util I will have to create another i18n app :)

**Comment by vizo** [comment]
@jagi i think the same, but this gives you even more flexibility ... Maybe some languages in the world have different form for negative numbers ... ;) who knows..

**Comment by fglueck** [comment]
OK, and how can I do this 
`{weeks, plural, <-1{past # weeks}=-1{last week}=0{current week}=1{next week}other{next # week} }`

**Comment by eemeli** [comment]
@fglueck You probably want to ask your question as a new discussion or somewhere else, rather than as a comment on an only vaguely-related issue that's been closed for almost a decade now.
