### ISSUE TITLE
Missing semicolons in locale definitions

### ISSUE THREAD

**Issue by jkrebs** [SlexAxton/messageformat.js#49]
We recently upgraded from 0.1.6 to 0.1.8 and ran into strange problems because the script was suddenly throwing "Uncaught TypeError: string is not a function".

Eventually we narrowed the problem down to missing semicolons at the end of the locale definition files for messageformat.js. We added the semicolons back and everything was working fine again.

**Comment by eemeli** [comment]
This was fixed/circumvented by #64.
