### ISSUE TITLE
Add debugging information to syntax exceptions

### ISSUE THREAD

**Issue by lostthetrail** [SlexAxton/messageformat.js#57]
Add debugging information to syntax exceptions.

When one of the many keys we have end up with a unsupported characters in it we get a syntax error looking like the following.

`SyntaxError: Expected "\\#", "\\u", "\\{", "\\}", "{", [^{}\\\0-\x1F \t\n\r] or end of input but "\\" found.`

Note it does not tell you which key/value is failing or even what the whole improper input was. (In this case it was \n)

**Comment by kavi87** [comment]
This is still an issue and a big one I think. Finding the faulty key in an object of 1000 keys without indication is hard to debug.

**Comment by eemeli** [comment]
This is now tracked here: messageformat/parser#9.

**Comment by kavi87** [comment]
@eemeli Ok, thanks, for now I've required the parser and tried-catch a call to the parse method on each value before feeding the translations to compile so that users can see their faulty keys.
