### ISSUE TITLE
Conditionally include text based on value null or not?

### ISSUE THREAD

**Issue by samuelneff** [SlexAxton/messageformat.js#60]
Is there any way with MessageFormat to make text conditional based on if a data value is null?  Can this be done with select?

I tried this but didn't work as I hoped:

``` javascript
mf.compile('{lastName}{firstName, select, undefined{} other{, }}{firstName}');
msg({lastName: 'Jones'});
```

Thanks,

Sam

**Comment by kavi87** [comment]
It is a bug in my opinion. Our users can write their own keys like `{ firstName } { lastName } - { secretAttribute }` but we do not want "John Doe - undefined" to be printed in some case. And handling the undefined case would be cumbersome in every keys. 

For now my solution is to use the parser and check that the args are in the context and replace absent variable with an empty string. 

A more useful syntax would be something like `{ firstName } { lastName } [[ - { secretAttribute } ]]` which would remove everything between the [[ ]] if one of the args inside is missing.

**Comment by eemeli** [comment]
@kavi87 Please file a new issue rather than commenting here, on an issue that's been closed for fouer years.
