### ISSUE TITLE
Consider Strawman Draft API?

### ISSUE THREAD

**Issue by rxaviers** [SlexAxton/messageformat.js#65]
If you are open to changing your API slightly (approximating to [Strawman Draft][])'s, we could have something like the below.

[Strawman Draft]: http://wiki.ecmascript.org/doku.php?id=globalization:messageformatting

```javascript
var messageFormat = new MessageFormat( locale, pattern [, fieldFormatters] );
var formattedMessage = messageFormat.format( params );
```

- **locale** is a string locale. E.g., `en`. (no changes to what you currently have)
- **pattern** is the message-format pattern. E.g., `{count, plural, one{...} other{...}}`. (no changes to what you currently have)
- **fieldFormatters** a key-value pair of fns. E.g., `{ plural: <fn>, number: <fn> }`. (it extends the way you currently get plural)

The optional **fieldFormatters** could be merged with a static/global/default one, e.g., `MessageFormat._fieldFormatters.<locale>`. So, you can keep setting the default plural function for English on your bundle.

#### Production mode (precompilation)

A formatted message is (obviously) a result of the [generated formatter][], which is the compiled pattern processed by two set of functions: (a) [runtime functions] (what's currently been called .functions()) and (b) the [fields functions][] (currently, the plural function).

[generated formatter]: https://github.com/SlexAxton/messageformat.js/blob/master/example/en/i18n.js#L16
[runtime functions]: https://github.com/SlexAxton/messageformat.js/blob/master/example/en/i18n.js#L6-L10
[fields functions]: https://github.com/SlexAxton/messageformat.js/blob/master/example/en/i18n.js#L1-L5

The [generated formatter][] doesn't embed the runtime functions nor the fields functions (which also makes sense to me). So, we can say the generated formatter is a function that depends on both of them:

```javascript
messageFormat.precompile(); // => function( runtimeFns, fieldsFns ) {
//  return <the generated formatter( params )>;
//}
```

#### The runtime bundle

Having distinguished the three layers above, generating the runtime bundle is not difficult. It could be accomplished in a variety of different ways:

- Embedding everything together similar to the current [example/en/i18n.js](https://github.com/SlexAxton/messageformat.js/blob/master/example/en/i18n.js)

Or:

    <script src="messageformat.runtime.js"></script>
    <script src="my-plural.runtime.js"></script>
    <script>
      MyGlobalName[ "key" ] = <precompiled>( MessageFormat, { plural: myPlural } );
    </script>

Or:

```javascript
// app.js
require.config({
  paths: {
    messageformat: "messageformat.runtime"
    "my-plural": "my-plural.runtime"
  }
});

require([ "./my-precompiled-message-formatter" ], function( messageFormatter ) {
  var message = messageFormatter({ count: 1 });
});

// my-precompiled-message-formatter.js
define([ "messageformat", "my-plural" ], function( MessageFormat, myPlural ) {
  return <precompiled>( MessageFormat, { plural: myPlural } );
});
```

OBS:

It's the plural library problem to generate its own plural runtime. The same way, it's the number formatter problem to generate its own runtime, the same for date formatter, currency formatter, etc.

**Comment by SlexAxton** [comment]
@eemeli - is there anything else we need to do in `0.3.0` to fully support this stuff. I think a lot of this has come in parts, but I haven't personally written a bunch of it, so I'd love to see if we were on the right track here.

Looks like we got `simpleArg` in there, and I'm cool not implementing `NumberFormat` or anything crazy as a dependency for making everything work out of the box (everyone is free to load the Intl-Polyfill).

**Comment by eemeli** [comment]
Yeah, I don't see anything more in the strawman draft that we could or should implement, as I don't think we should be changing the syntax. The `{VAR,fn[,opt]}` syntax we went with isn't in the draft, but I'd argue it to be closer to the current `simpleArg` and a maximally powerful minimal change. Polyfilling `NumberFormat` is indeed outside our scope, and seems like a rather different project.

I'm closing this as the original question seems rather well covered; should open separate issues for further discussion.

**Comment by rxaviers** [comment]
FWIW, I consider my request addressed, which was the parameterization of `formatters`. Thank you!
