### ISSUE TITLE
Bump to 0.2.2 and push to bower repository

### ISSUE THREAD

**Issue by oori** [SlexAxton/messageformat.js#72]
https://github.com/angular-translate/bower-angular-translate-interpolation-messageformat depends on old version 0.1.6.   
The current version on bower is quite broken.    but with the existing master and https://github.com/SlexAxton/messageformat.js/pull/71 the combo works again.

would be great if you could pull #71 and bump messageformat's version and into bower repo.

**Comment by SlexAxton** [comment]
I'm not sure if there's anything else to do for this. If you run `bower install messageformat` it installs the latest version and things seem to be in order. Closing but feel free to reopen if i've missed anything.

**Comment by oori** [comment]
No, this is obsolete.    Thanks.
