### ISSUE TITLE
Clear up pre-minified functions

### ISSUE THREAD

**Issue by SlexAxton** [SlexAxton/messageformat.js#75]
Hey @eemeli 

I was trying to write some docs, and then more recently help @csnover make a typescript meta description file for messageformat, and realized that there are a few parts of the code that I can't quite decipher anymore.

Pretty much the single variable name pre-minified functions.

Colin was able to come up with something that I think is mostly right: https://gist.github.com/csnover/60e5a41da7e1635391da

Is there anything you think we can do to make those functions more readable, and generally improve the readability of those parts of the code?

I think the *easiest* solution would be to write the function in complete long-form, and just stick it in a comment above the pre-minified one, but there's a chance that we don't *really* need to preminify so harshly. I trust your judgement on what you think would be best, but I'd love some help untangling these a little before we ship them out.

```js
    _n: function(v,o){if(isNaN(v))throw new Error("'"+v+"' isn't a number.");return v-(o||0)},
    _p: function(v,o,l,p,s){return v in p?p[v]:(v=l(v-o,s),v in p?p[v]:p.other)},
    _s: function(v,p){return v in p?p[v]:p.other},
```

Thanks!

**Comment by eemeli** [comment]
I forgot to note it here, but I'd say 6adf230 pretty much fixed this issue. @csnover, you were entirely right and I'd done some seriously premature optimization.
