### ISSUE TITLE
Norweigian should probably be nb, not no

### ISSUE THREAD

**Issue by SweVictor** [SlexAxton/messageformat.js#77]
Hi!

We noticed that the Norweigian language has been put under 'no', not 'nb'. The language to our knowledge is 'nb-NO' (Norweigian Bokmål - Norway). Similair discussion (by others and for another lib can be found here: https://github.com/adobe/brackets/issues/1602 )

Have we missed something or is 'nb' indeed correct?

Thanks
/Victor

**Comment by sudowork** [comment]
Hey @eemeli, any chance there will be a new version published with this fix in the near future?

**Comment by eemeli** [comment]
TBH, the only thing the version update's waiting for is the readme update. So I pushed a few of the commits I had pending from the past few weeks (Mainly making the output less terse; post-minification & post-compression there's not really any change in size) and called it [0.3.0-0](https://github.com/SlexAxton/messageformat.js/releases/tag/0.3.0-0).

@SlexAxton, the following command ought to publish this on npm as a prerelease, so it's installable by version tag, but won't count as `@latest`:

```
npm publish . --tag prerelease
```

**Comment by SlexAxton** [comment]
Done. Thanks guys. Also, @eemeli added you to npm owners.

**Comment by sudowork** [comment]
Thanks both of you!

**Comment by daghoidahl** [comment]
I think you've forgotten to publish this release? The latest bower package is still stuck at 0.2.2. I'm using the github url in the meantime.
