### ISSUE TITLE
precompile() method missing?

### ISSUE THREAD

**Issue by nzakas** [SlexAxton/messageformat.js#86]
The readme starts that there is a precompile() method (under Build Time Compilation), but no such method exists in the source. There is a _precompile() method, however. Can you clarify if this is a mistake?

**Comment by SlexAxton** [comment]
The master version is unreleased. It's more or less only blocked on my not having rewritten the readme. So while it is unfortunate, it's expected. I think @eemeli moved `_precompile` as a little legacy handle for people who were used to the old way. I think he wanted to just do `.compile().toString()` going forward. I'm all for that if the people want it. Certainly reduces the API surface area.

**Comment by SlexAxton** [comment]
(I also think it's bad to have an unreleased/unfinished version in master for so long, just got Lifed™.)

**Comment by eemeli** [comment]
Yeah, in `master` `precompile()` has become `_precompile()`, to give an indication that it's really an internal function; same with `parse()` becoming `_parse()`. 

For actual use, the `compile()` method should work for just about all use cases that take in text and output executable code or a live function.

@SlexAxton, should I consider looking at updating the readme, if my own Life™ allows it?

**Comment by SlexAxton** [comment]
Seems like that'd be wise. Happy to jump in as needed. Honestly you know more about the release, anyways.

**Comment by nzakas** [comment]
Thanks for the quick response.

**Comment by Autarc** [comment]
Aside of the outdated npm version, is it for your possible to compile pre-compiled functions at least on the master ? I've pulled the repository manual and still get parsing errors like:

 `"Error: Parser error: SyntaxError: Expected "," or "}" but "\"" found."`.

The serialized function I am calling with `mf.compile(...)` looks like this: 
```json
{
	"test": {
		"en": "function (d){return \"hello world\"}"
	}
}
```

**Comment by eemeli** [comment]
The problem with your string are the unescaped `{}` characters that are interpreted by messageformat as input. For an example of escaping them, see the [test code](https://github.com/SlexAxton/messageformat.js/blob/master/test/tests.js#L57-61).

This is something we ought to document better, though.

**Comment by Autarc** [comment]
Thanks, just pre-compiled using `.compile('hello world').toString()` and thought I could deserialize it directly. It works by escaping it afterwards.
