### ISSUE TITLE
useStaticFilesLoader with fallbackLanguage

### ISSUE THREAD

**Issue by sharanmunyal** [SlexAxton/messageformat.js#87]
I have a usecase where if the translation table for a language is absent and hence cannot be downloaded using useSaticFilesLoader, I want to fallback to 'en'. However 

$translateProvider
                .useStaticFilesLoader({
                    prefix: SourceConstant.FILES + 'lang/strings_',
                    suffix: '.json'
                })
                .registerAvailableLanguageKeys(['en'], {
                    'en_US': 'en',
                    'en_UK': 'en'
                })
                .fallbackLanguage('en')
                .determinePreferredLanguage();

This piece of code returns the translation ID instead of the english translation if table for the determined language is missing. Am I missing something ?

**Comment by eemeli** [comment]
That doesn't look like messageformat.js code at all, are you sure you're asking this in the right place? Perhaps what you want is [angular-translate](/angular-translate/angular-translate) instead?
