### ISSUE TITLE
Issue with plural offset?

### ISSUE THREAD

**Issue by ryanzec** [SlexAxton/messageformat.js#89]
So I was implementing this library in a new project and wanted to test out all the features myself and I think I found an issue.  I have this string:

```
You {NUM, plural, offset:1 =0{didn't like} zero{like} one{and 1 other person likes} other{and # others like}} this post
```

and the following code:

```javascript
window.i18n['desktop/home'].pluralOffset({
  NUM: 0
});
// OUTPUT: You like this post

window.i18n['desktop/home'].pluralOffset({
  NUM: 1
});
// OUTPUT: You and 0 others like this post

window.i18n['desktop/home'].pluralOffset({
  NUM: 2
});
// OUTPUT: You and 1 other person likes this post

window.i18n['desktop/home'].pluralOffset({
  NUM: 4
});
// OUTPUT: You and 3 others like this post

window.i18n['desktop/home'].pluralOffset({
  NUM: 8
});
// OUTPUT: You and 7 others like this post

window.i18n['desktop/home'].pluralOffset({
  NUM: 1000
});
// OUTPUT: You and 999 others like this post
```

I am not sure why when the value is 1, it is selecting the `other` version instead of the `zero` version (since `zero` should work off the offset number).

I am not hugely concerned about this since this is not a very common use case for me and I can work around it by doing `1{like}` instead of `zero{like}` but wouldn’t this be a bug?

I should mention I am using the CLI compiled version of the i18n.js file.

**Comment by eemeli** [comment]
The code is working as it should; there's a mistake in the documentation, which is undergoing a (slow) rewrite. The order of operations that's used is:

1. compare literal keys, if any match use it
2. otherwise, apply any offset
3. map the resulting value to a pluralization category, and use it

The problem with the [readme](/SlexAxton/messageformat.js#pluralformat---offset-extension) is that English doesn't use the `zero` case, so it never gets called.

Using your example, something like the following should work:
```
You {NUM, plural, offset:1
    =0{didn't like}
    =1{like}
    one{and 1 other person likes}
    other{and # others like}
} this post
```

**Comment by eemeli** [comment]
Also, could you verify that you're really getting `You like this post` for `{NUM: 0}` in your example? If so, exactly how did you install MessageFormat? Because that's a bug that I'm not able to replicate and we need to track down more precisely what causes it.

**Comment by ryanzec** [comment]
@eemeli Sorry about the first output, it was a mistake on my part and updated it to want I actually get (which is the correct text).

Also good to know that what I was seeing was a bug in the docs and not the code.
