### ISSUE TITLE
Generated code does not use short-circuit evaluation

### ISSUE THREAD

**Issue by vogelsgesang** [SlexAxton/messageformat.js#92]
The code generated for the messageformat expression
```
{cnt, select,
  unknown {an unknown number of persons}
  other {{cnt, plural,
    one {one person} other {# persons}
  }}
}
```
called with `cnt="unknown` throws the exception:
```
'unknown' isn't a number.
```

This exception is thrown from the runtime.number function ([messageformat.dev.js:193](https://github.com/SlexAxton/messageformat.js/blob/28c66e2eedc9beb1fe91d495bbef086b79c80eb3/lib/messageformat.dev.js#L193)) which is being called for the '#' sign.
First, I was surprised that this function was even called since the "unknown" path should have been taken. After further investigation it turned out that always all branches are evaluated even if only one of them is displayed in the end.

For example for the following template the plural function is evaluated three times, no matter which parameters are passed.
```
{GENDER, select,
  male {He found {NUM_RESULTS, plural,
            one {1 result}
          other {# results}
  }}
  female {She found {NUM_RESULTS, plural,
            one {1 result}
          other {# results}
  }}
  other {They found {NUM_RESULTS, plural,
            one {1 result}
          other {# results}
  }}
}
```

The reason for this behaviour lays in the structure of the generated code. The code for the first example:
```
return select(d.cnt, {
  unknown: "an unknown number of persons",
  other: plural(d.cnt, 0, pluralFuncs.en, {
    one: "one person",
    other: number(d.cnt)+" persons"
  })
});
```
Passing an object with all possible branches to `select` requires the complete evaluation of this object before calling `select`.

What do you think about this behavior? Should I invest some time to think about possible solutions?

**Comment by eemeli** [comment]
You're right, that is a problem. I can think of at least two solutions to the problem, neither of which is clearly better than the other:

First, we could do it "right" and wrap the values of `select`, `selectordinal` and `plural` statements into functions & modify the runtime functions to call these functions. Your example code for instance would then become:

```js
return select(d.cnt, {
  unknown: function() { return "an unknown number of persons"; },
  other: function() { return plural(d.cnt, 0, pluralFuncs.en, {
    one: function() { return "one person"; },
    other: function() { return number(d.cnt)+" persons"; }
  }); }
});
```

That would obviously look much nicer with ES6 arrow notation, but we can't realistically use that yet:

```js
return select(d.cnt, {
  unknown: () => "an unknown number of persons",
  other: () => plural(d.cnt, 0, pluralFuncs.en, {
    one: () => "one person",
    other: () => number(d.cnt)+" persons"
  })
});
```

Alternatively, we could consider `runtime.number()` doing a `throw` as an unwanted side effect, and remove it or place it behind some sort of "strict" option. That would keep the current (somewhat incorrect) non-short-circuiting behaviour, but would mask its effects as all the other runtime operations are purely functional.

I'm not sure what the difference would be in the computational load either approach would place on client systems, though the change is likely to be minimal. The former would increase output filesize somewhat, while the latter would reduce it by a few bytes.

@SlexAxton, opinions?

**Comment by SlexAxton** [comment]
I think the "right" way is pretty gzippable from a filesize concern and requires a good chunk fewer hacks. Let's do that.

**Comment by vogelsgesang** [comment]
Thanks for your quick response and the incredibly fast fix :+1:
