### ISSUE TITLE
SelectFormat accepts numerical values (f.e. "=0")

### ISSUE THREAD

**Issue by vogelsgesang** [SlexAxton/messageformat.js#93]
Currently, the following string (without my comment) is accepted by the parser and by the compiler
```
{var1, select, <-- I am using "select" instead of "plural" here
  =0 {invalid syntax for selects?}
  other {some text}
}
```

I am not sure if using the notation for explicit values form PluralFormat within SelectFormat is correct.
Hence, I am not sure if this is a bug or just an undocumented feature.

**Comment by eemeli** [comment]
Thank you, this was due to an incorrectly lax interpretation of the allowed keys in the parser. And while fixing that, I noticed that offsets weren't allowed for selectordinals, as they should be, so I fixed that too.
